#package overview
package_name: image_captioning

training_data_file: captions.txt
target: caption
pipeline_name: image_captioning
pipeline_save_file: image_captioning_output_v
features: image

# Alogrithm parameters
n_estimators: 100
max_depth: 10

ENCODER: "google/vit-base-patch16-224"
DECODER: "gpt2"
TRAIN_BATCH_SIZE: 8
VAL_BATCH_SIZE: 8
VAL_EPOCHS: 1
LR: 5e-5
SEED: 42
MAX_LEN: 128
SUMMARY_LEN: 20
WEIGHT_DECAY: 0.01
MEAN: 0.5 # (0.485, 0.456, 0.406)
STD: 0.5  # (0.229, 0.224, 0.225)
NUM_WORKERS: 4  # mp.cpu_count()
EPOCHS: 3
IMG_SIZE: 224
LABEL_MASK: -100
TOP_K: 1000
TOP_P: 0.95
EARLY_STOPPING: True
NGRAM_SIZE: 3
LEN_PENALTY: 2.0
NUM_BEAMS: 4
NUM_LOGGING_STEPS: 1024